[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_BASE_PATH = "" 

[[redirects]]
  from = "https://mindgoblin.org"
  to = "https://mindgoblin.gg"
  status = 301
  force = true